Fix missing context import in main function
libp2p/docs pull request #122
Opened 2022-01-04 16:31 UTC by kalikho

Imported "context"  in the main function and added the definition for ctx in the main function.

2022-01-05 07:27 UTC, marten-seemann requested changes

2022-01-05 07:27 UTC, marten-seemann commented on content/tutorials/getting-started/go.md
> +	ctx:=context.Background()
This is not gofmt'ed.

2022-03-02 14:34 UTC, tylerferrara approved these changes
I encountered the same problem in the go tutorial, which brought me here.
This PR needs some attention. 
@marten-seemann

2022-05-27 17:00 UTC, BigLep commented
Thanks for the contribution.  Closing because this fix was merged in another PR.

2022-05-27 17:00 UTC, closed without merging