Make sure tutorial will work for user
libp2p/docs pull request #173
Opened 2022-08-30 16:57 UTC by danicuki

Sometimes the user is using a different library version. I tested this tutorial many times before finding the right working version. 
It's good to have the version explicit in the docs.

2022-08-31 06:18 UTC, DannyS03 requested changes
thanks @danicuki, added some suggestions and would also suggest that this is at the beginning of the tutorial with the config instructions

2022-08-31 06:18 UTC, DannyS03 commented on content/tutorials/getting-started/javascript.md
> +## Working version
```suggestion
## Working versions

```

2022-08-31 06:18 UTC, DannyS03 commented on content/tutorials/getting-started/javascript.md
> +This tutorial was created and tested using these packages versions:
```suggestion
This tutorial uses the following js-libp2p package versions:
```

2022-08-31 06:18 UTC, DannyS03 commented on content/tutorials/getting-started/javascript.md
> +If you are using any different version of those above, make sure to change your code and adapt it to work for you.
```suggestion

> Modify your js-libp2p packages if you start to experience issues to those mentioned above.
```

2022-09-05 05:48 UTC, DannyS03 commented
@danicuki checking here if you're okay with the suggestions

2022-09-05 14:36 UTC, danicuki commented
yes! thanks!

2022-09-06 04:23 UTC, DannyS03 approved these changes

2022-09-06 08:16 UTC, marten-seemann reviewed
Putting version numbers here is a guarantee that we'll have a horribly outdated tutorial in a few months.

2022-09-06 08:32 UTC, DannyS03 commented
> Putting version numbers here is a guarantee that we'll have a horribly outdated tutorial in a few months.

we did mention that we'd setup jobs in the CI/CD to run the published tutorials which would notify of version changes or breaks. Or, if they are already running against the examples on each repo, we can pull in those updates

2022-09-06 08:40 UTC, marten-seemann commented
> we did mention that we'd setup jobs in the CI/CD to run the published tutorials which would notify of version changes or breaks.

A set of versions that work once won't break. That doesn't prevent them from becoming outdated though.

2022-09-06 12:58 UTC, danicuki commented
> 

I've added the version with the purpose of helping the developer to make it work. Because, I was one that suffered trying to make it work and had to discover the right version. You are right: doc gets outdated. The point is, it will get outdated even if we don't put any version in the tutorial. So we must keep it updated anyway. The version here has the purpose of making at least work, even when it is outdated :-)

2023-01-11 04:35 UTC, DannyS03 commented
with the stale nature of this change request and in correspondence with: https://github.com/libp2p/docs/issues/235, lets close this.

2023-01-11 04:35 UTC, closed without merging