feat: tls
libp2p/docs pull request #261
Opened 2022-12-05 05:37 UTC by DannyS03

## Context

- Adds content for libp2p TLS
- Part of https://github.com/libp2p/docs/issues/19

## Latest preview

Please view the latest Fleek preview [here]().

2022-12-06 05:04 UTC, p-shahi commented
@thomaseizinger can you help review this?

2022-12-06 05:14 UTC, marten-seemann requested changes

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +in a single round trip. Peers must authenticate each other’s identity during the
Not sure what key sharing is supposed to mean.
```suggestion
libp2p uses TLS 1.3 handshake to establish a secure connection between two peers. 
Peers authenticate each other’s libp2p peer ID during the handshake.
```

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +handshake and will abort if the client fails to authenticate.
```suggestion
```

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +{{< alert icon="💡" context="note" text="X.509 is an <a class=\"text-muted\" href=\"https://www.itu.int/en/Pages/default.aspx\"> ITU</a> standard defining the format of public key certificates that us
That's not really relevant, and super old anyway. The RFC is from 2005.

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +to those for which the signing of an X.509 certificate is specified.
```suggestion
In libp2p, peer authentication works by encoding the public key into the TLS certificate.
We designed the system such that we can authenticate key types that are usually not
supported by TLS stacks, such as sepc256k1 (which is a key type that can be used for
libp2p keys).
```

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +the private host key when signing the certificate.
That's very specific. I'd be ok with this just living in the specs, and not in the docs.

2022-12-06 05:14 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +establishment.
When processing the certificate, nodes derive the peer ID from the public key that they received,
and clients check that it matches the peer ID of the server they intended to connect to.

2022-12-07 23:50 UTC, thomaseizinger reviewed
Who is the audience of this document?

It starts out very high-level ("What is TLS") but gets detailed fairly quickly, explaining the messages in the handshake. Hence, for someone who's got no idea what TLS is, most of this document is probably overwhelming.

Given that libp2p is just _using_ libp2p in a particular configuration, (i.e. we didn't build it from scratch) I'd recommend the following:

- Retain the super high-level description (i.e. "What is TLS"). This provides some context on what we are talking about.
- From there, link to useful material for people that want to understand TLS in detail (RFC, perhaps Wikipedia for the historical bit)
- Describe that libp2p uses a particular subset, most notably TLS 1.3+
- For any details, we can link to the spec

Hope this helps :)

2022-12-08 04:34 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +## TLS 1.3 in libp2p
I think calling out the TLS version is high-level enough for a documentation page, but we definitely should link the spec (if we haven't already).

2022-12-12 21:32 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +version of TLS 1.3, referred to as TLS 1.3+.
Not really, we don't touch TLS internals.

2022-12-12 21:32 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +can use the encrypted connection to exchange data securely and privately.
That's how TLS always works, I find it confusing to call this out explicitly.

2022-12-12 21:32 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +In libp2p, peer authentication works by encoding the public key into the TLS certificate.
```suggestion
Peer authentication works by encoding the public key into the TLS certificate.
```

2022-12-12 21:32 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +> X.509 is an [ITU](https://www.itu.int/en/Pages/default.aspx) standard defining the format of public key certificates that use asymmetric cryptography for authentication. Certificate extensions were
I'd remove this sentence, it's not really relevant that TLS uses x509 to encode certificates.

2022-12-12 21:32 UTC, marten-seemann commented on content/concepts/secure-comm/tls.md
> +they received, and peers check that it matches the peer ID of the server they intend
```suggestion
they received. The node initiating the connection checks that it matches the peer ID of the node it intended
```

2022-12-14 10:22 UTC, thomaseizinger approved these changes
LGTM! Thanks for incorporating the review :)

2022-12-14 14:10 UTC, DannyS03 commented on content/concepts/secure-comm/tls.md
> +libp2p uses TLS 1.3 handshake to establish a secure connection between two peers.
```suggestion
libp2p uses the TLS 1.3 handshake to establish a secure connection between two peers.
```

2022-12-15 17:26 UTC, DannyS03 commented
thanks @thomaseizinger and @marten-seemann!

available to re-review @marten-seemann

2022-12-15 21:04 UTC, marten-seemann reviewed
It would be nice to have an introduction sentence saying that TLS is one of the security handshakes used to secure transports that don't have built-in security (TCP, WebSocket), and also mention that Noise is an alternative option. That would motivate the rest of this document.

Other than that, this looks good to me.

2022-12-19 05:55 UTC, DannyS03 commented
Added an introductory statement.

2022-12-23 12:42 UTC, merged