add: connections
libp2p/docs pull request #277
Opened 2023-01-03 02:15 UTC by DannyS03

## Context

- replaces https://github.com/libp2p/docs/pull/202; also up-to-date with new theme
- adds content about libp2p connection abstractions
- doc includes security protocol in multiaddr improvement
- resolves #32

## Latest preview

Please view the latest Fleek preview [here]().

2023-01-07 02:18 UTC, MarcoPolo requested changes

2023-01-07 02:18 UTC, MarcoPolo commented on content/concepts/fundamentals/connections.md
> +- The dialing peer sends a request to initiate a connection to the listening
This does't seem right. Reference https://github.com/libp2p/specs/blob/master/connections/README.md. The security protocol is negotiated in multistream not in the multiaddr.

2023-01-07 02:18 UTC, MarcoPolo commented on content/concepts/fundamentals/connections.md
> +- The peers negotiate which stream multiplexer to use by proposing and responding with
In some cases, the peer may include the stream muxer in the security handshake to save this roundtrip https://github.com/libp2p/specs/blob/master/connections/inlined-muxer-negotiation.md

2023-01-11 15:00 UTC, DannyS03 commented on content/concepts/fundamentals/connections.md
> +The listener's multiaddr determines the security protocol to be used on a connection
I jumped the gun here. Updated.

2023-01-11 15:15 UTC, DannyS03 commented on content/concepts/fundamentals/connections.md
> +- **Timeouts and retries**: If a connection or stream fails, libp2p will automatically retry
Hmm, I see what you mean. I modified to [this](https://github.com/libp2p/docs/pull/277/commits/86790d933aae91402b41a0ad0546732cdd14b44f#diff-d63d302b99ec29d312eb0614f7105d1df779526cc8eba743b9b8ad8a2b9c6cc8R55) (I believe this is what can be said).

2023-01-11 21:08 UTC, MarcoPolo commented on content/concepts/fundamentals/connections.md
> +- **Timeouts and retries**: If a connection or stream fails, libp2p will automatically retry
> libp2p only reconnects if you attempt to open a new stream 

I know I said this, but this is only true for go-libp2p. Not how rust-libp2p works. I think js-libp2p is similar to Go in this regard. Either way I think we should remove that line.

2023-01-11 22:12 UTC, MarcoPolo approved these changes
Looks good mod comments.

I think in general when we can point to something in specs we should instead of trying to re-explain it here.

2023-01-12 04:04 UTC, DannyS03 commented on content/concepts/introduction/core-abstractions/connections.md
> +> with a different protocol ID or with "na" to indicate that no common protocol
Yes

2023-01-15 18:53 UTC, merged