feat: content routing section
libp2p/docs pull request #291
Opened 2023-01-15 17:03 UTC by DannyS03

## Context

- Adds content routing section with initial documentation
- resolves #253

## Latest preview

Please view the latest Fleek preview [here]().

2023-01-26 01:08 UTC, DannyS03 commented
Link fixes and potential conflicts will be addressed in this PR once all associated material has been added.

2023-02-02 18:47 UTC, p-shahi requested changes

2023-02-02 19:00 UTC, DannyS03 commented on content/concepts/content-routing/kaddht.md
> +description: "Learn about Noise in libp2p."
This is updated in https://github.com/libp2p/docs/pull/293

2023-02-02 19:00 UTC, DannyS03 commented on content/concepts/content-routing/overview.md
> +description: "Learn about Noise in libp2p."
This is updated in https://github.com/libp2p/docs/pull/292

2023-02-02 19:13 UTC, p-shahi commented
Is it better practice and more explicit to convert this PR and any other labeled DNM as a draft pr?

2023-02-02 20:16 UTC, DannyS03 commented
@p-shahi yes, that makes sense - the idea in not making these "epic" PRs as drafts was to identify that the scope and structure changes aren't being drafted but ready for review, and the associated content have their own PRs.

2023-02-23 19:08 UTC, closed without merging