Add browser-to-browser WebRTC connectivity guide
libp2p/docs pull request #377
Opened 2024-05-14 15:41 UTC by 2color

- **initial draft of browser-to-browser guide**
- **progress**

2024-05-31 08:29 UTC, 2color commented
I just made Vercel previews public, so anyone opening this PR should be able [to preview](https://vercel.live/open-feedback/libp2p-docs-git-add-b2b-guide-ipfsdevs.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)

2024-06-04 11:19 UTC, achingbrain requested changes
This is great.  Some thoughts:

- Nothing here is browser specific, all of this applies to using the WebRTC transport to dial browsers from Node.js so it might be worth mentioning that?
  - Dialling browsers from non-browsers is only possible in js-libp2p right now, that's not really touched on here
- A lot of time is spent discussing how to automatically discover the listener peer's address, including using GossibSub to do so
  - It's rare to want to dial a specific peer for no reason, normally you want to dial a peer because they have something you want like an IPFS block, in which case you would have found their address during a search for providers
  - GossipSub is a big dep that causes the node to do a lot of work, it's inclusion comes with a lot of overhead
- Language/diagrams could be simplified by using roles (e.g. `Dialer`/`Listener`) instead of `Peer 1`/`Peer 2`
- The role of the `relay`/`bootstrapper` becomes a bit overloaded since it's used for connection establishment but also peer discovery
  - Maybe it could be two separate nodes to make it clear that the peer discovery part isn't a hard dependency of establishing the connection, it's just a way for the dialler to not have to copy/paste the multiaddr of the listener?
  - Alternatively peer discovery could be moved out of scope here and covered elsewhere?
  - The name "bootstrapper" is a bit confusing since what we normally refer to as "bootstrappers" are nodes run to enable populating routing tables
- The context switch between js and go for the relay is a bit jarring, also considering people reading this will like be JS people, but it is covered at the end of the article.
  - It's a little odd that we recommend using go-libp2p for the relay because it has WebTransport, but WebTransport is still pretty broken in browsers.  WebSockets, although tedious to configure, do work very well and are available everywhere.  Not sure there's a good answer here.

2024-06-04 15:29 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +While WebRTC is a solution to peer-to-peer connectivity in the context of browsers. Libp2p encompasses a wider scope with building blocks for building peer-to-peer apps that support WebRTC in additio
libp2p has its own notion of "protocols" so perhaps best to stay consistent and call them transports

2024-06-05 13:21 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +![diagram showing circuit relay](/webrtc-guide/circuit-relay-diagram.png)
yeah I'll switch to relay all over the place.

2024-06-07 11:22 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +![mesh topology](/webrtc-guide/mesh.png)
I removed the arrows to avoid getting into this detail in the diagram.

2024-06-07 12:16 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +  - **GossipSub Peer Discovery**: For browser peers to discover each other, they will need some mechanism to announce their multiaddresses to other browsers. GossipSub will help by relaying those pee
Adding a warning.

2024-06-07 13:31 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> ++import { circuitRelayTransport } from '@libp2p/circuit-relay-v2'
Fixed by changing the theme in 9571602713206a7b945c5a5efbe7ca99c1221d8b

![Screenshot 2024-06-07 at 3 30 42 pm](https://github.com/libp2p/docs/assets/1992255/082f3b04-6018-4b0f-bf3a-ec1dc7c702fb)

2024-06-07 14:08 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +![WebRTC connection flow diagram](/webrtc-guide/webrtc-diagram.svg)
I split it into two diagrams.

2024-06-10 09:40 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> +1. There's no prescribed mechanism in libp2p for how the two browsers discover each other's multiaddress. This guide will use a [dedicated GossipSub channel for the application where you publish your
Is GossipSub Peer Exchange implemented in the js-libp2p implementation?

2024-06-10 10:10 UTC, 2color commented on content/guides/getting-started/browser-to-browser.md
> ++      allowPublishToZeroTopicPeers: true,
I'll remove it since it's not needed for this guide.

2024-06-10 16:26 UTC, 2color commented
@achingbrain Mind giving this another review. I've addressed all your feedback and think this is ready to be merged.

2024-06-11 17:42 UTC, dhuseby reviewed
This is great!! I just cleaned up some passive voice for clarity.

2024-06-11 17:43 UTC, dhuseby commented
LGTM. Send it.

2024-06-12 09:16 UTC, merged