Fix typos and remove extra whitespaces
libp2p/docs pull request #99
Opened 2021-06-20 09:32 UTC by chutified

This PR fixes some typos and removes extra whitespaces at the end of lines.

2021-06-21 03:11 UTC, marten-seemann requested changes
I don't think it's necessary to fix typos in the Hugo example site.

2021-06-21 03:11 UTC, marten-seemann commented on content/concepts/protocols.md
> +all the registered match functions. If any returns `true`, the associated handler function will be invoked.
This is correct.

2021-06-21 17:06 UTC, chutified commented on content/concepts/protocols.md
> +all the registered match functions. If any returns `true`, the associated handler function will be invoked.
Yup, I changed it back.

2021-06-21 17:17 UTC, chutified commented
All changes made to the Hugo example site were rolled back.

2021-06-22 20:26 UTC, marten-seemann approved these changes

2021-06-22 20:26 UTC, merged

2021-06-22 20:26 UTC, marten-seemann commented
Thank you!